apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
    harness.io/pipelineName: hello-world-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: matjaramillo/matias-jaramillo-cicd:1.0
        ports:
        - containerPort: 8080
